---
title: "Workshops"
knitr:
  opts_chunk:
    echo: false
    message: false
    warning: false
---


## Introduction to Github for Researcher(s)

#### Learn how to use GitHub in your activities as a researcher from two GitHub Star researchers!

### About the course

**Date** November 18, 2024, 2:00 PM - 5:00 PM (GMT-3)
**Mode**: Online
**Enrollment**: [https://www.eventbrite.com.ar/e/1045617188157](https://www.eventbrite.com.ar/e/1045617188157)

**Language:** Spanish

This workshop is designed to introduce researchers to GitHub, a powerful platform for version control and collaboration. Participants will learn the basics of using GitHub to manage their research projects, including how to create and manage repositories, track changes, and collaborate with others.
Specific learning objectives include:
  - Understand the basic concepts of version control and how they apply to research workflows.
  - Gain hands-on experience in creating and managing GitHub repositories.
  - Explore the use of GitHub Issues and Projects to manage research tasks and communication within research teams.
  - Recognize the different components of a repository (readme, license, code of conduct, citations, among others).
In addition, the workshop will emphasize the relevance of GitHub in promoting open science, highlighting its role as a repository of code and data that supports transparency and reproducibility in research.
At the end of the workshop, participants will be able to integrate GitHub into their research workflows, enhancing both collaboration and open dissemination of scientific knowledge.
This tutorial is aimed at researchers from all disciplines interested in improving their project management and collaboration skills using GitHub. It is ideal for those who are part of research teams or groups, with some familiarity with research workflows, but no prior experience with GitHub is required.
### Requirements.
Participants must have a computer/laptop with Internet access and sufficient storage to install Git. They must have Git installed and a GitHub account created prior to the workshop.
- Install Git: [https://git-scm.com/](https://git-scm.com/)
- Create a free GitHub account: [https://github.com/](https://github.com/)

### Tutors
**Beatriz Milz** - Beatriz is a GitHub Star, and is currently a post-doctoral researcher at the Universidade Federal do ABC (UFABC), in Brazil. She holds a PhD in Environmental Sciences from the Universidade de São Paulo (USP). She is co-organizer of R-Ladies São Paulo and software review editor at rOpenSci.”
**Yanina Bellini Saibene** - Yani is a GitHub Star since 2022. She is Community Manager at rOpenSci, R-Ladies Project Leader and Vice President of the Board of The Carpentries. She lives in Argentina and teaches at Universidad Austral.



## Tutorial Satellite Data Analysis in R

#### Learn how to perform satellite data analysis with R combined with Machine Learninig techniques.

### About the course

**Date** November 18, 2024, 6:00 PM - 8:00 PM (GMT-3)

**Mode**: Online

**Enrollment**: [https://www.eventbrite.com.ar/e/1045614801017](https://www.eventbrite.com.ar/e/1045614801017)

**Language:** Spanish

Satellite data analysis in R, combined with Machine Learning techniques, opens new opportunities to interpret and leverage geospatial information.
This tutorial will address practical applications using R to process and analyze satellite imagery. It will demonstrate how to take advantage of specialized libraries in R, such as raster, sf and caret, to manipulate spatial data and build predictive models. The use of Machine Learning will allow the identification of patterns in large satellite data sets, applying algorithms such as decision trees, SVM and Random Forest.
Real examples in fields such as precision agriculture, environmental monitoring and land surface change detection will be highlighted. The presentation will emphasize the importance of integrating satellite data in decision making and how these techniques allow a more efficient and accurate analysis of our environment from space.


### Tutor

**Gladis Choque Ulloa**

I have a master's degree in statistics from the Federal University of Rio Grande do Sul, Brazil, I have more than 5 years of experience in the world of data and research. I am currently a scholarship student in the PhD in Statistics with focus in Data Science at the University of São Paulo, Brazil.

I specialize in time series and classification models in Machine Learning. In addition, I have written articles on predictive models and classification, and I have had the honor of winning the Massachusetts Institute of Technology (MIT) International Competition in 2020, I was dominated for the Women That Build Awards as Outstanding Woman in Data by Globant in 2022, I was Expomentor in the NASA Space Apps Challangue Peru in 2023, winner of the Science Clubs Brazil 2020 and winner as best research paper of the “Clean Water Science Network” program at the University of Texas, USA. Founder of the data community Women in Datalab, Top Voice Data Science on Linkedln and data influencer under the name “Datos con Gladys” and “Gladys Data Club”.



## Tutorial: Working with larger than memory data in R with Arrow and DuckDB

#### Learn to analyze large datasets with Arrow, DuckDB & Duckplyr in R.Speed up workflows on your laptop using tidyverse-style data manipulation

### About the course

**Date** November 19, 2024, 10:00 AM - 12:00 AM (GMT-3)

**Mode**: Online

**Enrollment**: [https://www.eventbrite.com.ar/e/1044938257457](https://www.eventbrite.com.ar/e/1044938257457)

**Language:** English

While datasets are growing larger, recent advances in technologies such as Apache Arrow and DuckDB are making the analysis of datasets that used to require complex infrastructure accessible to anyone.

Using the {arrow}, {duckdb}, and {duckplyr} packages opens up the door to analyzing gigabytes of data in seconds using the same interface as with the {tidyverse}. By learning just a few concepts, R users can enjoy working easily with larger-than-memory datasets directly from their everyday computer.
In this tutorial, will analyze real data to explore formats used to store these large datasets on disks, how Arrow and DuckDB can be leveraged to analyze data, and how these tools integrate with the {tidyverse} interface.

After attending this tutorial, learners will:
  - Understand when using Arrow or DuckDB can help speed up a data analysis
  - Describe how Arrow and DuckDB can work with datasets that are larger than memory
  - Recognize the type of data manipulations that benefit the most from leveraging tools like Arrow and DuckDB
  - Decide which package ({arrow}, {duckdb}, or {duckplyr}) is best suited for their data analysis
  - Develop their own data analysis using Arrow or DuckDB

This tutorial is aimed at everyone who needs to analyze datasets that are larger than the memory they have available on their everyday computer or who is interested in learning how to speed up the analysis of large datasets.
Participants who don’t have access to HPC will particularly benefit from this tutorial as the tools used can easily be installed on a regular laptop and provide good performance.

### Requirements.
Participants should already be familiar with data manipulation with the {tidyverse} (knowing how to use the 5 most common {dplyr} verbs for data analysis: mutate(), select(), filter(), summarize(), arrange() combined with group_by()).

**Software**: R >= 4.1.0
**packages**: arrow, duckdb, duckplyr, tidyverse, tictoc.

### Tutor
**François Michonneau** is an educator who loves to work with data and putting R in production. He has been using R for over 20 years and maintains several packages on CRAN. After being part of the leadership at The Carpentries for 5 years, he worked at Voltron Data for a couple of years. He's currently looking for his next role.

## Tutorial Take your graphs with ggplot2 to the next level

#### Learn how to create clear, informative and captivating visualizations for your data analysis.

### About the course

**Date** November 19th, 2024, 2:00 PM - 4:30 PM (GMT-3)

**Mode**: Online

**Enrollment**: [https://www.eventbrite.com.ar/e/1045608201277](https://www.eventbrite.com.ar/e/1045608201277)

**Language:** Spanish

Creating clear, informative and captivating visualizations is an undisputed endeavor within data analytics, both within academia and industry. However, the vast majority of tutorials or initial R courses tend to only explain how the ggplot2 graph grammar works, without covering the potential of the aesthetic parameters that help to nonverbally communicate the graph's objective. In this workshop we will show how to edit text and colors, both specifically and from the use of palettes, and how to adapt the chart to specific publication criteria.

#### General learning objective:
Participants can adapt their graphics to the publication requirements of a journal or other academic format.

### Specific learning objectives:
Participants can modify the textual elements of the graphics.
Participants can edit the appearance of graphics both by selecting specific colors and using palettes.
Participants can specify the export dimensions of graphics.

The tutorial is intended for a wide audience looking to take their graphics to the next level by customizing labels and text, colors and details of the graphics, especially to prepare them in the best way for presentations or publications. In particular, this workshop aims to help those who know how to make a basic graphic, but are unable to adapt it to their specific needs or to get the graphic to show exactly what they want.

### Requirements

In order to be able to follow the tutorial activities smoothly, it is necessary to have some experience, even if it is initial, with R and RStudio and with the ggplot2 package.

You should have a computer with R and R Studio installed and up to date. They should also install the tidyverse package, which includes the ggplot2 package, which is what the course will be about.

### Tutors

**Noelia A. Stetie** is a Professor and Bachelor of Arts at the University of Buenos Aires (UBA) and a doctoral fellow of CONICET. She is dedicated to the study of psycholinguistic processing at the sentence level. She collaborates in research projects at the UBA and has worked as a teacher at that institution, at the Universidad Nacional de José C. Paz and at teacher training institutes. She is a certified instructor at The Carpentries and has given several workshops on data analysis with R. She teaches courses focused on data analysis and the application of psycholinguistic theories to teaching practice.

**Macarena S. Quiroga** holds a Master's degree in Cognitive Psychology and Learning from the Latin American Faculty of Social Sciences (FLACSO), a BA in Literature from the University of Buenos Aires (UBA) and a doctoral fellowship from CONICET. She is dedicated to the study of the comprehension and production of vocabulary in young children. She teaches at the National University of Hurlingham. She is a certified Trainer and Instructor of The Carpentries and has given several workshops on data analysis with R.



## Ecological Niche and Potential Species Distribution Tutorial with R

#### The tutorial will cover the basic theory of ecological niche and potential species distribution modeling and its main methodologies.

### About the course

**Date**: November 19, 2024, 6:00 PM - 9:00 PM (GMT-3)

**Modality**: Online

**Enrollment**: [https://www.eventbrite.com.ar/e/1045601130127](https://www.eventbrite.com.ar/e/1045601130127)

**Language:** English

The tutorial will cover the basic theory of ecological niche modeling (ENM) and species distribution potential (SDM) and their main methodologies. By the end of the predominantly practical course, participants will have the ability to run the models and understand their results, as well as choose and apply the correct methodology depending on the purpose of their type of study and data. The tutorial will be mainly practical, with some theoretical moments. All modeling processes, calculations, graphs and maps will be carried out with R. Participants will learn to use Maxent modeling algorithm, through the {flexsdm} package to develop the models and the {tmap} package will be used to generate maps.

### Objectives:
  - To present the theoretical bases of the models that can be used;
  - Dscuss the advantages and limitations of the models in the context of different applications;
  - To introduce the ways of correctly conducting an ecological niche or species distribution modeling study for various purposes;
  - Initiate the use of geographic distribution modeling of species using R;

Students, researchers and professionals at any stage of their career with an interest in developing and applying species distribution and/or ecological niche models in a reproducible and automated way. Participants should be used to working with computers, have a good internet connection and preferably a webcam, as the live online sessions are intended to be highly interactive. Previous basic experience with R is strongly desirable, although not strictly mandatory. All R scripts will be provided and explained in detail.

### Requirements
- Latest version of R and RStudio and packages that will be sent by email. 32MB RAM desirable, but it is possible to run the script with 16MB.

### Tutor

**George Amaro** is a researcher at the Brazilian Agricultural Research Corporation (Embrapa), in the area of economics and modeling, and is a leader and member of invasive species distribution modeling projects, a reviewer for international journals on the subject, with extensive experience in R and having participated as an author and co-author of several works related to SDM/ENM.

## Optimizando Shiny: Consejos y Trucos de Rendimiento

#### Aprende cómo optimizar el rendimiento de aplicaciones desarrolladas con R Shiny de la mano de expertos de Appsilon.

### About the course

**Date** November 18, 2024, 10:00 AM - 1:00 PM (GMT-3)

**Modalidad**: Online

**Enrollment**: [https://www.eventbrite.cl/e/optimizando-shiny-consejos-y-trucos-de-rendimiento-tickets-1045595392967](https://www.eventbrite.cl/e/optimizando-shiny-consejos-y-trucos-de-rendimiento-tickets-1045595392967)

**Language:** Spanish

En este workshop, exploraremos cómo optimizar el rendimiento de aplicaciones desarrolladas con R Shiny, desde mejorar la velocidad de respuesta hasta la escalabilidad.

A través de ejemplos prácticos y técnicas avanzadas, identificaremos los cuellos de botella más comunes, para minimizar tiempos de carga y gestionar grandes volúmenes de datos de manera eficiente.

También abordaremos las mejores prácticas para optimizar tanto el código como la estructura de la aplicación, incluyendo el uso adecuado de reactividad, carga de datos, y comunicación con el navegador.

Al finalizar el taller, tendrás las herramientas necesarias para transformar tus aplicaciones Shiny, haciéndolas más rápidas, ligeras y listas para brindar una mejor experiencia de usuario.


Este taller está dirigido a desarrolladores y analistas que buscan mejorar el rendimiento de sus aplicaciones Shiny, con un enfoque práctico y orientado a resultados.

### Requirements

R 4.1.0 o mayor, RStudio instalado. 8GB RAM (deseable), internet estable (deseable). Git instalado (deseable). Alternativamente, tener una cuenta en posit.cloud.

### Tutor

**Samuel Calderon** actualmente trabaja como R shiny developer en Appsilon. Previamente, su desempeño profesional ha sido en el sector público peruano, participando en iniciativas de recojo, análisis y sistematización de información con miras a mejorar la calidad de los servicios brindados a la ciudadanía en temas de lucha contra el tráfico ilícito de drogas, mejora de la calidad de la educación superior universitaria, lucha contra la corrupción y medición de la pobreza monetaria.

Linkedin: <https://www.linkedin.com/in/samuelcalderon/>

## Despliegue Continuo con R, GitHub y Quarto: Implementando Buenas Prácticas

#### Aprende cómo implementar un flujo de trabajo de despliegue continuo para modelos de datos en R utilizando GitHub y Quarto

### About the course

**Date**: November 18, 2024, 06:00 PM - 08:00 PM (GMT-3)

**Modalidad**: Online

**Enrollment**: [https://www.eventbrite.cl/e/despliegue-continuo-con-r-github-y-quarto-implementando-buenas-practicas-tickets-1046364954747](https://www.eventbrite.cl/e/despliegue-continuo-con-r-github-y-quarto-implementando-buenas-practicas-tickets-1046364954747)

**Language:** Spanish

Este taller tiene como objetivo enseñar a los participantes a implementar un flujo de trabajo de despliegue continuo para modelos de datos en R utilizando GitHub y Quarto. Al final de la sesión, los asistentes serán capaces de:

Configurar un entorno de R en GitHub Actions para automatizar la ejecución de scripts.
Instalar y gestionar dependencias de R de manera eficiente.
Generar y renderizar informes en Quarto, facilitando la presentación de resultados.
Integrar buenas prácticas de DevOps en sus flujos de trabajo para mejorar la colaboración y la calidad del código.

La relevancia de este taller radica en la creciente necesidad de automatización en el análisis de datos y la ciencia de datos. Aprender a utilizar GitHub Actions y Quarto no solo optimiza el trabajo en equipo, sino que también permite a los participantes implementar soluciones robustas y escalables para la evaluación de métricas y el análisis de resultados. Este conocimiento es fundamental para quienes buscan mejorar la reproducibilidad de sus proyectos y la eficiencia de sus procesos de análisis.


El taller está dirigido a profesionales y estudiantes de áreas como ciencia de datos, estadística, análisis de datos y programación en R. También es relevante para investigadores y desarrolladores interesados en optimizar sus flujos de trabajo mediante la automatización y la implementación de buenas prácticas de DevOps.

Los participantes deben tener conocimientos básicos de programación en R y familiaridad con Git y GitHub. También es recomendable que tengan conocimientos basicos en generación de documentos en R, ya sea usando Rmarkdown o Quarto.

### Requirements

Para participar de forma óptima en el taller de Despliegue Continuo con R, GitHub y Quarto, los asistentes deben contar con una computadora portátil (Windows, macOS o Linux) y tener instalado el software necesario, que incluye R, RStudio, Git y Quarto. Además, es importante tener acceso a Internet y una cuenta de GitHub previamente creada. Se recomienda asegurarse de tener acceso a los archivos de ejemplo que se utilizarán durante el taller. Aunque no es estrictamente necesario, tener conocimientos básicos de R y Git, así como familiaridad con Markdown, será útil para aprovechar al máximo la experiencia.

### Tutor

**Sebastián Egaña Santibáñez** es Magíster en Finanzas por la Universidad de Chile, Licenciado en Filosofía por la Universidad Alberto Hurtado y Ingeniero Comercial por la Universidad Santo Tomás, Chile.

Es un profesional destacado en Ciencia de Datos, con una sólida trayectoria como docente universitario y experiencia en asesoría especializada. Ha contribuido significativamente a la formación académica y a la aplicación práctica del análisis de datos, ofreciendo soluciones innovadoras y estratégicas en diversos contextos.

## Desarrollo de Paquetes en R: Desde la Idea hasta la Implementación

#### Aprende cómo desarrollar paquetes de R, como implementarlos y distribuirlos.

### About the course

**Date**: November 19, 2024, 10:00 AM - 1:00 PM (GMT-3)

**Modalidad**: Online


**Enrollment**: [Desarrollo de Paquetes en R](https://www.eventbrite.cl/e/desarrollo-de-paquetes-en-r-desde-la-idea-hasta-la-implementacion-tickets-1046361845447)


**Language:** Spanish

Este taller ofrece una guía integral sobre el desarrollo de paquetes en R, cubriendo todo el proceso, desde la concepción de la idea hasta la implementación técnica y la distribución en plataformas como CRAN.

El objetivo es brindar a los asistentes una comprensión clara y práctica de cómo crear un paquete en R que cumpla con los estándares de calidad y pueda ser utilizado por la comunidad científica y de desarrollo.

A lo largo de la presentación, exploraremos las mejores prácticas para el diseño, documentación, pruebas, y publicación de paquetes. Se proporcionarán ejemplos y demostraciones en vivo para que los asistentes puedan adquirir habilidades prácticas aplicables en sus propios proyectos.

El tutorial esta enfocado en usuario de R, desarrolladores de R, investigadores, científicos de datos y profesionales de otras disciplinas que pueden tomar su conocimiento, experiencias y datos y convertirlos en un paquete de R para su publicación en el CRAN.


### Requirements

PC o Laptop con R, RStudio y RTools (windows) instalados, paquetes: devtools, available, usethis, testthat.

### Tutor

**Renzo Cáceres Rossi**, es un especialista en el lenguaje de programación R, ya ha participado en el Latin R 2022 con la ponencia Introducción a RMarkdown, ha dictado tutoriales, conferencias en diversas universidades en Latinoamérica a través del IEEE.

Es creador de contenido sobre ciencia de datos a través de su canal de YouTube
<https://www.youtube.com/c/RenzoCaceresRossi>
